In [89]:
import pandas as pd
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
from IPython.display import display, HTML
from sklearn.impute import SimpleImputer
import warnings
warnings.filterwarnings("ignore")

In [164]:
books_df=pd.read_csv("C:\\Users\\mamat\\Documents\\Master of science\\2nd sem\\Data Mining\\Project\\Preprocessed_data.csv")

cols=books_df.columns

print('ColumnName, DataType, MissingValues')
for i in cols:
    print(i, ',', books_df[i].dtype,',',books_df[i].isnull().any())
    
display(HTML(loans.head(10).to_html()))

ColumnName, DataType, MissingValues
Unnamed: 0 , int64 , False
user_id , int64 , False
location , object , False
age , float64 , False
isbn , object , False
rating , int64 , False
book_title , object , False
book_author , object , False
year_of_publication , float64 , False
publisher , object , False
img_s , object , False
img_m , object , False
img_l , object , False
Summary , object , False
Language , object , False
Category , object , False
city , object , True
state , object , True
country , object , True

In [166]:
books_df['state']=books_df.state.replace('[^a-zA-Z]', np.nan, regex=True)
books_df['city']=books_df.city.replace('[^a-zA-Z]',  np.nan, regex=True)
books_df['country']=books_df.country.replace('[^a-zA-Z]',  np.nan, regex=True)

In [242]:
books_test=books_df.copy(deep=True)

In [243]:
books_test.groupby(by='city').fillna(books_test['state'].mode()[0],inplace=True)

Empty DataFrame
Columns: []
Index: []

In [258]:
books_test.groupby(by='city')['state'].agg(pd.Series.mode)

city
a                 scotland
aaaaaaa             alaska
aachen                 nrw
aalborg        nordjylland
aalen                   []
                  ...
zweenfurth         sachsen
zwickau            sachsen
zwijndrecht             []
zwingenberg             []
zwolle          overijssel
Name: state, Length: 9446, dtype: object

city
a                 scotland
aaaaaaa             alaska
aachen                 nrw
aalborg        nordjylland
aalen                   []
                  ...
zweenfurth         sachsen
zwickau            sachsen
zwijndrecht             []
zwingenberg             []
zwolle          overijssel
Name: state, Length: 9446, dtype: object

In [255]:
temp[['city']=='addison']

KeyError: False

In [231]:
books_test.state.fillna(books_test['state'].mode()[0],inplace=True)

In [235]:
books_test[books_test['user_id']==108681]

,Unnamed: 0,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
874175,874175,108681,"berlin, , germany",25.0,3404146018,0,Vier Gedecke und ein Liebesfall.,Tiffanie Darke,2001.0,LÃ?Â¼bbe,http://images.amazon.com/images/P/3404146018.0...,http://images.amazon.com/images/P/3404146018.0...,http://images.amazon.com/images/P/3404146018.0...,9,9,9,berlin,california,germany

In [244]:
books_test.state.isna().sum()

220926

## DATA PREPROCESSING

In [250]:
books_test.city.value_counts().sort_values(ascending=False)

toronto     15124
chicago      9079
seattle      8605
ottawa       8330
olympia      8090
            ...
arta            1
g               1
segovia         1
espanola        1
winslow         1
Name: city, Length: 9446, dtype: int64

books_test.state.value_counts().sort_values(ascending=False)

In [3]:
imputer = SimpleImputer(missing_values=np.NaN, strategy='most_frequent')

loans['Years in current job']=imputer.fit_transform(loans['Years in current job'].values.reshape(-1,1))[:,0]

# calculate mean value by ignoring missing values
mean_Credit_Score=loans['Credit Score'].mean(skipna=True)
mean_Annual_Income=loans['Annual Income'].mean(skipna=True)
mean_Months_since_last_delinquent=loans['Months since last delinquent'].mean(skipna=True)
mean_Maximum_Open_Credit=loans['Maximum Open Credit'].mean(skipna=True)
mean_Bankruptcies=loans['Bankruptcies'].mean(skipna=True)
mean_Tax_Liens=loans['Tax Liens'].mean(skipna=True)

# replace missing values in numerical variables by using mean value #################################
loans["Credit Score"].fillna(loans["Credit Score"].mean(), inplace=True)
loans["Annual Income"].fillna(loans["Annual Income"].mean(), inplace=True)
loans["Months since last delinquent"].fillna(loans["Months since last delinquent"].mean(), inplace=True)
loans["Maximum Open Credit"].fillna(loans["Maximum Open Credit"].mean(), inplace=True)
loans["Bankruptcies"].fillna(loans["Bankruptcies"].mean(), inplace=True)
loans["Tax Liens"].fillna(loans["Tax Liens"].mean(), inplace=True)

# check again whether there are missing values
print('ColumnName, DataType, MissingValues')
for i in cols:
    print(i, ',', loans[i].dtype,',',loans[i].isnull().any())

display(HTML(loans.head(10).to_html()))

ColumnName, DataType, MissingValues
Loan Status , object , False
Current Loan Amount , int64 , False
Term , object , False
Credit Score , float64 , False
Annual Income , float64 , False
Years in current job , object , False
Home Ownership , object , False
Purpose , object , False
Monthly Debt , float64 , False
Years of Credit History , float64 , False
Months since last delinquent , float64 , False
Number of Open Accounts , int64 , False
Number of Credit Problems , int64 , False
Current Credit Balance , int64 , False
Maximum Open Credit , float64 , False
Bankruptcies , float64 , False
Tax Liens , float64 , False

## TRANSFORMATION

In [4]:
# 04. Data transformation ##########################################################
    
loans_transform=loans.copy(deep=True)   
# print out and display dataframe as tables in HTML
display(HTML(loans_transform.head(5).to_html()))

# convert categorical data to numerical data, e.g., Degree #########################

print(loans_transform['Years in current job'].dtype)
print(loans_transform['Home Ownership'].dtype)
print(loans_transform['Purpose'].dtype)

df_dummies_years=pd.get_dummies(loans_transform['Years in current job'])
df_dummies_ownership=pd.get_dummies(loans_transform['Home Ownership'])
df_dummies_purpose=pd.get_dummies(loans_transform['Purpose'])

# add binary variables to dataframe
loans_transform=loans_transform.join(df_dummies_years)
loans_transform=loans_transform.join(df_dummies_ownership)
loans_transform=loans_transform.join(df_dummies_purpose)

# remove the original categorical variable
loans_transform=loans_transform.drop('Years in current job',1)
loans_transform=loans_transform.drop('Home Ownership',1)
loans_transform=loans_transform.drop('Purpose',1)

loans_transform=loans_transform.replace('Fully Paid',1)
loans_transform=loans_transform.replace('Charged Off',0)

loans_transform=loans_transform.drop('1 year',1)
loans_transform=loans_transform.drop('HaveMortgage',1)
loans_transform=loans_transform.drop('Home Improvements',1)

display(HTML(loans_transform.head(5).to_html()))

object
object
object

C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/1836214357.py:23: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  loans_transform=loans_transform.drop('Years in current job',1)
C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/1836214357.py:24: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  loans_transform=loans_transform.drop('Home Ownership',1)
C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/1836214357.py:25: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  loans_transform=loans_transform.drop('Purpose',1)
C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/1836214357.py:30: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  loans_transform=loans_transform.drop('1 year',1)
C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/1836214357.py:31: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  loans_transform=loans_transform.drop('HaveMortgage',1)
C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/1836214357.py:32: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  loans_transform=loans_transform.drop('Home Improvements',1)

## NORMALIZATION

In [5]:
# 03. Normalization ################################################################################

# find numeric columns
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
# get column names
cols_numeric = loans_transform.select_dtypes(include=numerics).columns.tolist()
# get column indices
cols_numeric_index=[loans_transform.columns.get_loc(col) for col in cols_numeric]
print('Numerical column names:\n',cols_numeric)
print('Numerical column indices:\n',cols_numeric_index)
    
# create a copy first
df_norm=loans_transform.copy(deep=True)

# Normalization method 1 = min-max normalization
# API, https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
loans_transform[cols_numeric]=scaler.fit_transform(loans_transform[cols_numeric])
display(HTML(loans_transform.head(10).to_html()))

# Normalization method 2 = Min-max normalization [0,1]
for col in cols_numeric:
    df_norm[col]=(loans_transform[col]-loans_transform[col].min())/(loans_transform[col].max()-loans_transform[col].min())

Numerical column names:
 ['Loan Status', 'Current Loan Amount', 'Credit Score', 'Annual Income', 'Monthly Debt', 'Years of Credit History', 'Months since last delinquent', 'Number of Open Accounts', 'Number of Credit Problems', 'Current Credit Balance', 'Maximum Open Credit', 'Bankruptcies', 'Tax Liens']
Numerical column indices:
 [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

## KNN

In [6]:
#KNN (Distance Measure: Euclidian distance)
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

y = df_norm['Term'] # define label as nominal values
le = preprocessing.LabelEncoder()
le.fit(y)
y_encoded = le.transform(y)

df_norm['Term'] = y_encoded
x = df_norm.drop('Term',1)
y = df_norm['Term'] 

display(HTML(df_norm.head(10).to_html()))

x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2)

# build and eval models
from sklearn import neighbors
from sklearn.metrics import accuracy_score
# API， https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from matplotlib import pyplot as plt

# API for KNeighborsClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

for k in range(5, 10, 2): 
    clf=neighbors.KNeighborsClassifier(k, weights='uniform')
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print('K =', k, ', Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

# By N-fold cross evaluations ###############################################
from sklearn.model_selection import cross_val_score

for k in range(5, 10, 2): 
    clf=neighbors.KNeighborsClassifier(k, weights='uniform')
    acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
    pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
    rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
    f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
    print('K =', k, ', Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1',round(f1,3))

C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/3387013642.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = df_norm.drop('Term',1)

K = 5 , Accuracy:  0.704 , Precision:  0.704 , Recall:  0.704 , F1 Score:  0.808
K = 7 , Accuracy:  0.712 , Precision:  0.712 , Recall:  0.712 , F1 Score:  0.817
K = 9 , Accuracy:  0.711 , Precision:  0.711 , Recall:  0.711 , F1 Score:  0.818
K = 5 , Accuracy:  0.7013199999999999 , Precision 0.7567421485888863 , recall 0.8641424598700207 , f1 0.8068838019601603
K = 7 , Accuracy:  0.70574 , Precision 0.7516268477731469 , recall 0.8848881035940874 , f1 0.8128306034497758
K = 9 , Accuracy:  0.71187 , Precision 0.7492954566242938 , recall 0.9031547339387759 , f1 0.8190618659194545

In [7]:
#KNN (Distance Measure: Manhattan Distance)
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

y = df_norm['Term'] # define label as nominal values
le = preprocessing.LabelEncoder()
le.fit(y)
y_encoded = le.transform(y)

df_norm['Term'] = y_encoded
x = df_norm.drop('Term',1)
y = df_norm['Term'] 

display(HTML(df_norm.head(10).to_html()))

x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2)
# build and eval models
from sklearn import neighbors
from sklearn.metrics import accuracy_score
# API， https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from matplotlib import pyplot as plt

# API for KNeighborsClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

for k in range(5, 10, 2): 
    clf=neighbors.KNeighborsClassifier(k, weights='uniform',p=1)
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print('K =', k, ', Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))
    
# By N-fold cross evaluations ###############################################
from sklearn.model_selection import cross_val_score

for k in range(5, 10, 2): 
    clf=neighbors.KNeighborsClassifier(k, weights='uniform',p=1)
    acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
    pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
    rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
    f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
    print('K =', k, ', Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

C:\Users\mamat\AppData\Local\Temp/ipykernel_4356/2919072404.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = df_norm.drop('Term',1)

K = 5 , Accuracy:  0.716 , Precision:  0.716 , Recall:  0.716 , F1 Score:  0.818
K = 7 , Accuracy:  0.723 , Precision:  0.723 , Recall:  0.723 , F1 Score:  0.825
K = 9 , Accuracy:  0.727 , Precision:  0.727 , Recall:  0.727 , F1 Score:  0.83
K = 5 , Accuracy:  0.715 , Precision 0.763 , recall 0.877 , f1 score 0.816
K = 7 , Accuracy:  0.719 , Precision 0.758 , recall 0.897 , f1 score 0.822
K = 9 , Accuracy:  0.722 , Precision 0.754 , recall 0.913 , f1 score 0.826

## LOGISTIC REGRESSION

In [27]:
#Logistic regression (lbfgs)
import pandas as pd
import numpy as np
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2)
clf=LogisticRegression(penalty='l2',solver='lbfgs')
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
print("Hold out evaluation")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))
      
x=df_norm.drop('Term',axis=1)
y=df_norm['Term']
# by N-fold cross validation
clf=LogisticRegression()
acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
print("N fold cross validation")
print(' Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Hold out evaluation
Accuracy:  0.721 , Precision:  0.721 , Recall:  0.721 , F1 Score:  0.836
N fold cross validation
 Accuracy:  0.721 , Precision 0.728 , recall 0.979 , f1 score 0.835

In [28]:
#Logistic regression (sag)
import pandas as pd
import numpy as np
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2)
clf=LogisticRegression(penalty='l2',solver='sag')
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
#acc=accuracy_score(y_pred, y_test)
print('hold-out evaluation: ')
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))
      
x=df_norm.drop('Term',axis=1)
y=df_norm['Term']
# by N-fold cross validation
clf=LogisticRegression()
acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
print("N-fold cross validation")
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

hold-out evaluation:
Accuracy:  0.718 , Precision:  0.718 , Recall:  0.718 , F1 Score:  0.833
N-fold cross validation
Accuracy:  0.721 , Precision 0.728 , recall 0.979 , f1 score 0.835

## NEURAL NETWORKS

In [30]:
# 07. Neural Networks ###########################################################
# Preprocessing: same requirements as KNN, not necessary for normalization

# API
# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html

from sklearn.neural_network import MLPClassifier

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2)
clf=MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(200,), random_state=1)
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

x=df_norm.drop('Term',axis=1)
y=df_norm['Term']
# by N-fold cross validation
clf=MLPClassifier(solver='lbfgs', alpha=1e-4,hidden_layer_sizes=(100,8), random_state=1)
acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Accuracy:  0.744 , Precision:  0.744 , Recall:  0.744 , F1 Score:  0.845
Accuracy:  0.735 , Precision 0.745 , recall 0.962 , f1 score 0.84

In [31]:
# 07. Neural Networks,hidden_layers,power_t ###########################################################
# Preprocessing: same requirements as KNN, not necessary for normalization

# API
# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html


from sklearn.neural_network import MLPClassifier

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2)
clf=MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(200,),power_t=0.25,random_state=1,max_iter=200)
clf=clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

x=df_norm.drop('Term',axis=1)
y=df_norm['Term']
# by N-fold cross validation
clf=MLPClassifier(solver='lbfgs', alpha=1e-4,hidden_layer_sizes=(200,8),power_t=0.25,random_state=1,max_iter=200)
pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Accuracy:  0.733 , Precision:  0.733 , Recall:  0.733 , F1 Score:  0.839
Accuracy:  0.735 , Precision 0.741 , recall 0.966 , f1 score 0.839

## NAIVE BAYES

In [35]:
# 03. Naive Bayes Classifier ################################################################################
# Requirements: 1). nominal features; 2). assumption of conditionally indepenence
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.model_selection import cross_val_score

# Pre-processing ###############################################
print('Column data types:\n',loans.dtypes)
loans_nb=loans.copy(deep=True)

# convert numerical to categorical data, e.g., Age #################################
loans_nb['Current Loan Amount'] = pd.cut(loans_nb['Current Loan Amount'],3)
loans_nb['Credit Score'] = pd.cut(loans_nb['Credit Score'],3)
loans_nb['Annual Income'] = pd.cut(loans_nb['Annual Income'],3)
loans_nb['Monthly Debt'] = pd.cut(loans_nb['Monthly Debt'],3)
loans_nb['Years of Credit History'] = pd.cut(loans_nb['Years of Credit History'],3)
loans_nb['Months since last delinquent'] = pd.cut(loans_nb['Months since last delinquent'],3)
loans_nb['Number of Open Accounts'] = pd.cut(loans_nb['Number of Open Accounts'],3)
loans_nb['Number of Credit Problems'] = pd.cut(loans_nb['Number of Credit Problems'],3)
loans_nb['Current Credit Balance'] = pd.cut(loans_nb['Current Credit Balance'],3)
loans_nb['Maximum Open Credit'] = pd.cut(loans_nb['Maximum Open Credit'],3)
loans_nb['Bankruptcies'] = pd.cut(loans_nb['Bankruptcies'],3)
loans_nb['Tax Liens'] = pd.cut(loans_nb['Tax Liens'],3)

display('Data Example',HTML(loans_nb.head(5).to_html()))

# by hold-out evaluation ###########################################################
y=loans_nb['Term']
le = preprocessing.LabelEncoder()
le.fit(y)
y_encoded = le.transform(y) # encode nominal labels to integers #####################################

# transform categorical data to numerical data, i.e., one-hot encoding
print(loans_nb.dtypes)
loans_nb=pd.get_dummies(loans_nb.drop('Term',axis=1))
#loans_nb['Term']=y_encoded
#display(HTML(loans_nb.head(5).to_html()))
#print(y_encoded[0:10])

print('starting model build and evaluations...')

# API for GaussianNB
# https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB

x_train, x_test, y_train, y_test = train_test_split(loans_nb, y_encoded, test_size=0.2)

clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
# in the following coding example, we use accuracy only as the example
print("Hold out method")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

# by N-fold evaluation ###########################################################
print("N fold Method")
clf = GaussianNB()
acc=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Column data types:
 Loan Status                      object
Current Loan Amount               int64
Term                             object
Credit Score                    float64
Annual Income                   float64
Years in current job             object
Home Ownership                   object
Purpose                          object
Monthly Debt                    float64
Years of Credit History         float64
Months since last delinquent    float64
Number of Open Accounts           int64
Number of Credit Problems         int64
Current Credit Balance            int64
Maximum Open Credit             float64
Bankruptcies                    float64
Tax Liens                       float64
dtype: object

'Data Example'

Loan Status                       object
Current Loan Amount             category
Term                              object
Credit Score                    category
Annual Income                   category
Years in current job              object
Home Ownership                    object
Purpose                           object
Monthly Debt                    category
Years of Credit History         category
Months since last delinquent    category
Number of Open Accounts         category
Number of Credit Problems       category
Current Credit Balance          category
Maximum Open Credit             category
Bankruptcies                    category
Tax Liens                       category
dtype: object
starting model build and evaluations...
Hold out method
Accuracy:  0.296 , Precision:  0.296 , Recall:  0.296 , F1 Score:  0.059
N fold Method
Accuracy:  0.291 , Precision 0.849 , recall 0.023 , f1 score 0.044

In [34]:
# 03. Naive Bayes Classifier ################################################################################
# Requirements: 1). nominal features; 2). assumption of conditionally indepenence
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.model_selection import cross_val_score

# Pre-processing ###############################################
print('Column data types:\n',loans.dtypes)
loans_nb=loans.copy(deep=True)

# convert numerical to categorical data, e.g., Age #################################
loans_nb['Current Loan Amount'] = pd.cut(loans_nb['Current Loan Amount'],3)
loans_nb['Credit Score'] = pd.cut(loans_nb['Credit Score'],3)
loans_nb['Annual Income'] = pd.cut(loans_nb['Annual Income'],3)
loans_nb['Monthly Debt'] = pd.cut(loans_nb['Monthly Debt'],3)
loans_nb['Years of Credit History'] = pd.cut(loans_nb['Years of Credit History'],3)
loans_nb['Months since last delinquent'] = pd.cut(loans_nb['Months since last delinquent'],3)
loans_nb['Number of Open Accounts'] = pd.cut(loans_nb['Number of Open Accounts'],3)
loans_nb['Number of Credit Problems'] = pd.cut(loans_nb['Number of Credit Problems'],3)
loans_nb['Current Credit Balance'] = pd.cut(loans_nb['Current Credit Balance'],3)
loans_nb['Maximum Open Credit'] = pd.cut(loans_nb['Maximum Open Credit'],3)
loans_nb['Bankruptcies'] = pd.cut(loans_nb['Bankruptcies'],3)
loans_nb['Tax Liens'] = pd.cut(loans_nb['Tax Liens'],3)

display('Data Example',HTML(loans_nb.head(5).to_html()))

# by hold-out evaluation ###########################################################
y=loans_nb['Term']
le = preprocessing.LabelEncoder()
le.fit(y)
y_encoded = le.transform(y) # encode nominal labels to integers #####################################

# transform categorical data to numerical data, i.e., one-hot encoding
print(loans_nb.dtypes)
loans_nb=pd.get_dummies(loans_nb.drop('Term',axis=1))
#loans_nb['Term']=y_encoded
display(HTML(loans_nb.head(5).to_html()))
print(y_encoded[0:10])

print('starting model build and evaluations...')

# API for GaussianNB
# https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB

x_train, x_test, y_train, y_test = train_test_split(loans_nb, y_encoded, test_size=0.2)

clf = GaussianNB(var_smoothing=1)
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
# in the following coding example, we use accuracy only as the example
print("Hold-out Method:")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

# by N-fold evaluation ###########################################################
clf = GaussianNB(var_smoothing=1)
acc=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Column data types:
 Loan Status                      object
Current Loan Amount               int64
Term                             object
Credit Score                    float64
Annual Income                   float64
Years in current job             object
Home Ownership                   object
Purpose                          object
Monthly Debt                    float64
Years of Credit History         float64
Months since last delinquent    float64
Number of Open Accounts           int64
Number of Credit Problems         int64
Current Credit Balance            int64
Maximum Open Credit             float64
Bankruptcies                    float64
Tax Liens                       float64
dtype: object

'Data Example'

Loan Status                       object
Current Loan Amount             category
Term                              object
Credit Score                    category
Annual Income                   category
Years in current job              object
Home Ownership                    object
Purpose                           object
Monthly Debt                    category
Years of Credit History         category
Months since last delinquent    category
Number of Open Accounts         category
Number of Credit Problems       category
Current Credit Balance          category
Maximum Open Credit             category
Bankruptcies                    category
Tax Liens                       category
dtype: object

[1 1 1 0 1 1 1 0 1 1]
starting model build and evaluations...
Hold-out Method:
Accuracy:  0.72 , Precision:  0.72 , Recall:  0.72 , F1 Score:  0.835
Accuracy:  0.719 , Precision 0.728 , recall 0.974 , f1 score 0.833

## DECISION TREE

In [36]:
# 04. Decision Trees and Random Forest ##########################################################
# Preprocessing: 1). encode labels; 2). convert numerical to categorical data and then encoding
# Tips: same preprocessing with the operations in Naive Bayes

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

# API for DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(loans_nb, y_encoded, test_size=0.2)
clf=DecisionTreeClassifier(criterion='entropy', max_depth=10) # note: there are many parameters in API
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
#acc=accuracy_score(y_pred, y_test)
print("Hold out method")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))
#print('Tree Accuracy by hold-out evaluation: ',acc)

# by N-fold cross validation
acc=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='f1').mean()

print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))     
#print("Tree Accuracy by N-fold Cross Validation:",acc)

Hold out method
Accuracy:  0.719 , Precision:  0.719 , Recall:  0.719 , F1 Score:  0.835
Accuracy:  0.72 , Precision 0.724 , recall 0.988 , f1 score 0.836

In [38]:
# 04. Decision Trees and Random Forest ##########################################################
# Preprocessing: 1). encode labels; 2). convert numerical to categorical data and then encoding
# Tips: same preprocessing with the operations in Naive Bayes

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

# API for DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(loans_nb, y_encoded, test_size=0.2)
clf=DecisionTreeClassifier(criterion='gini', max_depth=8) # note: there are many parameters in API
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
acc=accuracy_score(y_pred, y_test)
print("Hold out method")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

# by N-fold cross validation
acc=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='f1').mean()

print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))     
#print("Tree Accuracy by N-fold Cross Validation:",acc)

Hold out method
Accuracy:  0.717 , Precision:  0.717 , Recall:  0.717 , F1 Score:  0.834
Accuracy:  0.721 , Precision 0.724 , recall 0.99 , f1 score 0.837

## ADABOOST CLASSIFIER

In [43]:
# Ada boost classifier ##########################################################

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier

# API for DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(loans_nb, y_encoded, test_size=0.2)
clf=AdaBoostClassifier(n_estimators=100) # note: there are many parameters in API
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
acc=accuracy_score(y_pred, y_test)
print("Hold out method")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

# by N-fold cross validation
acc=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='f1').mean()

print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))     
#print("Tree Accuracy by N-fold Cross Validation:",acc)

Hold out method
Accuracy:  0.724 , Precision:  0.724 , Recall:  0.724 , F1 Score:  0.84
Accuracy:  0.722 , Precision 0.722 , recall 0.999 , f1 score 0.838

In [44]:
# Ada boost classifier ##########################################################

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier

# API for DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(loans_nb, y_encoded, test_size=0.2)
clf=AdaBoostClassifier(n_estimators=400) # note: there are many parameters in API
clf1=clf.fit(x_train, y_train)
y_pred=clf1.predict(x_test)
acc=accuracy_score(y_pred, y_test)
print("Hold out method")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))

# by N-fold cross validation
acc=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, loans_nb, y_encoded, cv=5, scoring='f1').mean()

print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))     
#print("Tree Accuracy by N-fold Cross Validation:",acc)

Hold out method
Accuracy:  0.721 , Precision:  0.721 , Recall:  0.721 , F1 Score:  0.838
Accuracy:  0.722 , Precision 0.722 , recall 0.999 , f1 score 0.838

## RANDOM FOREST

In [40]:
# Example of randomForest = bagging method of decision trees
tree = DecisionTreeClassifier()
# Note: you can use tree only or the random forest for the purpose of evaluations
# API, https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html?highlight=baggingclassifier
bag = BaggingClassifier(tree, n_estimators=100, max_samples=0.8, random_state=1)
acc=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))     

# Example of randomForest = bagging method of decision trees,n_estimators
tree = DecisionTreeClassifier()
bag = BaggingClassifier(tree, n_estimators=400, max_samples=0.8, random_state=1)
acc=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='precision').mean()
rcl=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='recall').mean()
f1=cross_val_score(bag, loans_nb, y_encoded, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Accuracy:  0.717 , Precision 0.726 , recall 0.977 , f1 score 0.833
Accuracy:  0.717 , Precision 0.726 , recall 0.977 , f1 score 0.833

## FEATURE REDUCTION

In [41]:
# 06. Feature reduction #################################################################

# Example of PCA

from sklearn.decomposition import PCA

#display(HTML(x.head(10).to_html()))
# convert all features to numerical, in order to apply PCA
# df_dummies_nationality=pd.get_dummies(df_transform['Nationality'])
# print(df_dummies_nationality.head(5))

# # add binary variables to dataframe
# df_transform=df_transform.join(df_dummies_nationality)
# remove the original categorical variable
# df_transform=df_transform.drop('Nationality',1)
# remove on extra binary variable
# df_transform=df_transform.drop(' China',1)


x = df_norm.drop('Term', 1)
y = df_norm['Term']
display(HTML(x.head(10).to_html()))

# feature extraction
# API, https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
pca = PCA(n_components=10)
fit = pca.fit(x)

# summarize components
# print("Explained Variance: %s") % fit.explained_variance_ratio_
print('Explained variance: ', fit.explained_variance_ratio_)
print('\nPCAs:\n', fit.components_)

# select PCA and output new features
# for example, we choose the top-3 PCAs

PCAs = pca.fit_transform(x)
PCAs_selected = PCAs[:,:3]
df_PCAs = pd.DataFrame(data=PCAs_selected, columns=['PC1','PC2','PC3'])
df_PCAs['Term']=y

display(HTML(df_PCAs.head(10).to_html()))

# write new data to external files
#df_PCAs.to_csv('Data_Students_PCA.csv', sep=',')

Explained variance:  [0.2336639  0.11879498 0.0952008  0.09421898 0.06205429 0.04643312
 0.04414028 0.04062311 0.03651872 0.03227792]

PCAs:
 [[-5.04119815e-02 -9.58656959e-03  9.40102184e-03 -1.36287382e-03
  -8.74466162e-03 -3.73055327e-02  4.94299957e-03 -1.33401276e-02
  -5.92135637e-04 -2.95871640e-03 -2.00492114e-04 -5.35408415e-04
  -2.06149077e-04 -2.41995852e-01  5.32399313e-02  3.69682527e-02
   2.39452856e-02  1.89486970e-02  9.56769842e-03  5.05293916e-03
   1.72441831e-04  3.12531150e-04  6.11425682e-02 -6.84991924e-01
   8.07690034e-03  6.76853403e-01  9.66964805e-04  3.06861484e-03
   2.98920331e-03  6.63384052e-03  6.42590576e-04  4.90343594e-04
   1.52093816e-02  5.03171204e-03  7.56679920e-04  1.56589856e-03
   1.76048276e-02  8.23028645e-07  5.01129205e-04  8.91940077e-04
   9.91386485e-04]
 [-8.00092675e-02 -2.31702138e-02  1.67812264e-02 -2.27204859e-04
   1.58158882e-03  4.20709655e-02  1.59242288e-04 -4.39789128e-04
   2.96307299e-03  8.75058478e-04 -5.44815636e-05  5.09996519e-03
   5.07894002e-04  9.06129275e-01 -1.41390407e-01 -1.25090504e-01
  -8.52476124e-02 -1.01240839e-01 -8.21220247e-02 -8.17194003e-02
  -6.60278022e-02 -5.46176501e-02 -1.08800379e-01 -1.96824001e-01
   4.11849664e-02  1.55617857e-01 -1.30504004e-02 -4.15252861e-03
  -1.05575894e-02  1.33305019e-01 -8.72191123e-04 -4.27310798e-03
  -2.70090280e-02 -3.96682663e-04 -2.80508277e-03 -4.44890309e-04
  -2.56948479e-02 -9.56165642e-05 -1.70173691e-03 -5.44172465e-06
  -1.09748778e-03]
 [ 3.75383532e-01  1.05820238e-01 -9.00799147e-02  3.42739273e-04
  -6.43213924e-03  5.74860660e-03 -1.95724469e-03 -1.78955699e-02
   1.34499519e-03 -1.80022599e-03  8.40039918e-05  1.38982783e-03
   3.42265000e-04  1.41310761e-01 -1.29497962e-02 -9.51071969e-03
  -1.67839497e-03 -1.49833738e-02 -1.97562363e-02 -2.68683266e-02
  -1.83717586e-02 -1.95995341e-02 -8.88207678e-03 -7.32727068e-02
   5.85771395e-02  6.56373720e-03  5.21966458e-02  2.35327473e-02
   4.62594018e-02 -8.34967813e-01  3.34757161e-03  3.93628808e-02
   1.32012042e-01  2.08176468e-02  1.16708027e-02  4.89368114e-03
   2.93077314e-01  2.73827792e-04  8.22743551e-03  3.32011090e-03
   3.87651310e-03]
 [-8.50664255e-01 -2.64014133e-01  1.90099653e-01 -3.16421618e-04
  -1.19688982e-03 -4.23494431e-03 -3.83461124e-03 -4.12152157e-03
   5.28445492e-04 -7.55278794e-04 -3.15725283e-05 -7.26699080e-04
   5.61187927e-04 -9.96311484e-03 -5.70965291e-03 -5.44590237e-03
   4.82780296e-03  2.56241753e-03  2.89860126e-03  1.14740432e-03
   1.75488868e-03  1.61842281e-03  4.91922619e-03  2.52588045e-02
   2.17057919e-02 -4.94905206e-02  3.31012695e-02  9.77274428e-03
   1.58487705e-02 -3.79066471e-01  1.19990256e-03  1.92137967e-02
   4.94592516e-02  7.75373444e-03  5.46598626e-03  2.46605589e-03
   1.36331568e-01  2.52555831e-04  6.97023733e-03  1.77087999e-03
   1.37896757e-03]
 [ 1.30243430e-03 -3.52648119e-03  1.65722588e-03 -5.55276176e-04
  -1.97026193e-03  6.52676158e-03 -5.21847249e-04  9.21653355e-04
   5.20596547e-04  3.29056533e-04  1.13349581e-04  2.28906163e-04
   2.11528882e-04 -5.46191130e-02  4.39106722e-03  4.26279100e-03
   5.10843467e-03  3.49028540e-03  6.99204913e-03  6.02688190e-03
   1.00801385e-02  5.48717846e-03  5.67626430e-03 -3.90590441e-01
   8.11145663e-01 -4.24839301e-01 -7.47115335e-03 -6.52749309e-04
   1.02360333e-04  6.04877173e-02 -3.41335274e-04 -3.05477395e-03
  -1.54416088e-02  4.67173414e-03 -3.27222845e-04 -1.70416541e-03
  -4.03686466e-02 -1.99521644e-05 -1.40214838e-03 -5.79709410e-04
  -5.53103213e-04]
 [-2.77547032e-01  9.54748679e-01  6.33608130e-02 -5.78365236e-05
  -2.03060594e-04  4.98150422e-03  7.08923231e-04  1.54342429e-03
  -1.96558510e-04  6.48844610e-05 -7.80147107e-05 -5.80353045e-04
   1.39879209e-04  3.64541957e-03  7.09042184e-02 -4.32857441e-02
  -6.88729568e-03 -1.44051249e-03  3.99072679e-03 -6.89384546e-03
  -5.07247832e-03 -1.18875820e-04 -1.17789720e-02  2.31844348e-03
   3.48116036e-03 -5.85549458e-03 -1.48234672e-03 -2.00626110e-04
   1.73516692e-03 -1.07531778e-02  1.82532513e-04  2.21643764e-03
   1.01367414e-03 -4.91745589e-04  9.29629801e-04  6.47414177e-04
  -2.37552448e-03 -6.57221268e-05  1.32354725e-03 -2.19323680e-04
   6.73760322e-04]
 [ 1.65639465e-02 -7.94405992e-02 -3.71331850e-03  1.13327686e-04
   3.78051439e-04 -1.34333226e-05 -3.24396533e-03  1.03529500e-03
  -2.44131117e-05  5.59988506e-05 -7.88263119e-05 -7.93732493e-05
   1.03608959e-04  3.26543407e-02  8.85532894e-01 -3.06023539e-01
  -5.85964900e-02 -8.47020419e-02 -4.62386761e-02 -4.25202737e-02
  -2.64907135e-02 -2.02801866e-02 -3.14249209e-01  2.78690178e-03
   1.66347417e-03 -4.23223922e-03 -7.71382975e-05  2.11205285e-03
  -2.52954922e-03 -6.46848038e-04 -6.02058260e-04  3.10626926e-03
  -4.06281304e-03 -3.71919176e-05  8.42990371e-04 -1.50881632e-04
  -4.15562307e-03 -1.06267116e-04  4.09403412e-04  1.30697084e-04
   1.11521872e-04]
 [-1.31677644e-02  1.94900206e-02  8.56712785e-03  7.95833462e-05
   1.11599677e-03 -3.21201874e-03  2.03978496e-03  9.05588907e-04
   1.31208478e-03 -2.02585127e-04 -5.41398176e-05  2.11851838e-03
   4.71336473e-05  7.88237247e-03  3.46748142e-03  7.21712411e-01
  -4.78634506e-03 -1.19029585e-02 -7.02062721e-03 -8.19128080e-03
  -5.80067433e-03 -4.12530216e-03 -6.91166456e-01 -1.36970495e-02
   1.48143207e-03  1.14739814e-02  2.08064913e-03 -1.80054336e-03
  -1.33790616e-03 -2.27366757e-03 -1.84355116e-03  1.53278957e-03
  -3.73642713e-03  2.72067297e-03  1.69296500e-04 -7.28392740e-04
  -2.54786600e-04  1.72553925e-04  9.84773827e-04  1.31219717e-05
  -3.95128455e-04]
 [ 7.95916671e-03 -2.46104819e-03 -6.60415134e-03 -3.46342758e-06
   1.17733814e-03  1.20265555e-03  8.46587392e-03  6.13876207e-04
   1.27713473e-03 -5.07922764e-05 -6.02470870e-05  1.60791484e-03
   2.08497991e-04 -5.02058444e-02 -2.52940186e-01 -4.72597218e-01
   2.48993196e-01  5.79220709e-01  1.54710120e-01  1.38688210e-01
   7.07524821e-02  4.95339703e-02 -5.10497332e-01 -2.27486397e-02
  -1.55482271e-03  2.32792120e-02 -6.37390803e-04 -1.31876343e-03
   3.75066630e-04 -7.85777616e-03 -5.47803842e-04  3.23631345e-04
  -6.25033582e-03  2.47364683e-03 -7.62175999e-04 -8.32040077e-04
   7.40325641e-03  5.41920948e-05  3.88404731e-04  1.21737007e-03
  -4.73968861e-04]
 [-2.52261272e-03 -4.43782080e-03  8.89036103e-04  1.71759545e-05
  -6.64942429e-04  2.04753673e-03 -3.03863990e-03 -6.14169374e-05
  -1.37581799e-03  1.22336847e-05  1.02206541e-04 -1.96220810e-03
  -8.29795423e-05  3.68344935e-02  1.13017050e-01  1.56738079e-01
  -5.92042386e-01  6.98370700e-01 -2.25628978e-01 -1.93586354e-01
  -7.44466763e-02 -4.83034871e-02  1.61866124e-01  4.99931509e-03
   3.17367880e-03 -7.80928890e-03  4.93467626e-03  2.86219446e-04
  -3.35014343e-03 -1.43914286e-03  2.79928136e-04  7.24189549e-04
   1.30433335e-02 -8.66202036e-04 -8.96794534e-06  8.31229304e-04
  -1.59198221e-02  4.92703190e-05  7.74399984e-04  8.47832466e-04
   4.86861490e-04]]

## SVM

In [42]:
# 05. SVM ###########################################################
# Preprocessing: same requirements as KNN, not necessary for normalization

from sklearn.svm import SVC

# API for SVC
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html?highlight=svc#sklearn.svm.SVC

x = df_PCAs.drop('Term', 1)
y = df_PCAs['Term']
display(HTML(x.head(10).to_html()))

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
clf=SVC(kernel='linear', C=1E10) # C is large -> hard margin; C is small -> soft margin
clf1=clf.fit(x_train[0:100], y_train[0:100])
y_pred=clf1.predict(x_test)
print("Hold out method")
print('Accuracy: ', round(accuracy_score(y_test, y_pred),3), ', Precision: ', round(precision_score(y_test, y_pred, average='micro'),3),', Recall: ', round(recall_score(y_test, y_pred, average='micro'),3), ', F1 Score: ', round(f1_score(y_test,y_pred),3))


x=df_PCAs.drop('Term',axis=1)
y=df_PCAs['Term']
# by N-fold cross validation
clf=SVC(kernel='poly', C=1E10)
acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()

print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))     
clf=SVC(kernel='rbf', C=1E10)
acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
pcs=cross_val_score(clf, x, y, cv=5, scoring='precision').mean()
rcl=cross_val_score(clf, x, y, cv=5, scoring='recall').mean()
f1=cross_val_score(clf, x, y, cv=5, scoring='f1').mean()
print('Accuracy: ',round(acc,3),', Precision', round(pcs,3),', recall', round(rcl,3),', f1 score',round(f1,3))

Hold out method
Accuracy:  0.574 , Precision:  0.574 , Recall:  0.574 , F1 Score:  0.664
Accuracy:  0.64 , Precision 0.767 , recall 0.751 , f1 score 0.746
Accuracy:  0.68 , Precision 0.799 , recall 0.751 , f1 score 0.768